### ISSUE TITLE
Might wanna add an integration of GitHub into the server so you can see the issues listed on the repository.

### ISSUE THREAD

**Issue by Komorebiao** [notoriouslogank/harbinger#19]
I know you can do this. Idk how, or if you want to, but I know you can.

**Comment by notoriouslogank** [comment]
So like, a place for 'Known Bugs' or something?  If you try running the !help command, there's a bit of info about Issues; see if that's what you're looking for. Or do you just mean pull the list of issues as opposed to having to navigate to GitHub? @Komorebiao

**Comment by Komorebiao** [comment]
I mean pull the list of issues as opposed  to coming to discord. I know there's tons of bots that  can post a feed of stuff. Again that's if that's a feature you would be interested in. If you wanted to do that you might be even able to get a live feed that posts into a specific chat and lists off the things reported under the issues tab once you've assigned them a label...

sounds like more work tho soooo ¯\_(ツ)_/¯ if u wanna
