### ISSUE TITLE
Missing Help Commands (Dev)

### ISSUE THREAD

**Issue by notoriouslogank** [notoriouslogank/harbinger#80]
Missing !help() commands for all cogs.dev commands.

**Comment by notoriouslogank** [comment]
#83

**Comment by PedramHaeri** [comment]
Hi I would like to try and fix this issue. could you please assign it to me?

**Comment by notoriouslogank** [comment]
@PedramHaeri Unfortunately this particular issue is already closed. Honestly, I would've been happy to let you work on it as you're the first person who's ever offered to contribute to anything of mine, but I didn't even realize you'd commented (since I wasn't anticipating anyone to have any interest in contributing, I wasn't keeping an eye on my notifications).

That said, if you have any interest in contributing going forward, I'd be more than happy to assign something to you.

Thanks a bunch for your interest!
